//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Czasopismo : Materiał_biblioteczny
{
	public virtual Periodyk Rodzaj_periodyku
	{
		get;
		set;
	}

	public virtual int Ilość_stron
	{
		get;
		set;
	}

	public virtual {
		get;
		set;
	}

}

