//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Czytelnik
{
	public virtual string Imię
	{
		get;
		set;
	}

	public virtual string Nazwisko
	{
		get;
		set;
	}

	public virtual string Adres
	{
		get;
		set;
	}

	public virtual string Nr_telefonu
	{
		get;
		set;
	}

	public virtual {
		get;
		set;
	}

}

