//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Egzemplarz_casopisma
{
	public virtual readonly int Kod_egzemplarza
	{
		get;
		set;
	}

	public virtual bool Egzemplarz_dostępny
	{
		get;
		set;
	}

}

