//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Film : Materiał biblioteczny
{
	public virtual Nośnik Rodzaj_nośnika
	{
		get;
		set;
	}

	public virtual time Długość_nagrania
	{
		get;
		set;
	}

}

