//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Konto
{
	public virtual Stan_konta Stan
	{
		get;
		set;
	}

	public virtual readonly int Numer_id
	{
		get;
		set;
	}

	public virtual int Ilość_wypożyczeń
	{
		get;
		set;
	}

	public virtual int Ilość_rezerwacji
	{
		get;
		set;
	}

	public virtual money Saldo_kar
	{
		get;
		set;
	}

	public virtual {
		get;
		set;
	}

	public virtual {
		get;
		set;
	}

	public virtual void Opłacenie_kary()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Zamknięcie_konta()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Odblokowanie_konta()
	{
		throw new System.NotImplementedException();
	}

}

