//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class Wypożyczenie
{
	public virtual date Data_wypożyczenia
	{
		get;
		set;
	}

	public virtual date Data_zwrotu
	{
		get;
		set;
	}

	public virtual {
		get;
		set;
	}

	public virtual {
		get;
		set;
	}

	public virtual {
		get;
		set;
	}

	public virtual date Określenie_daty_zwrotu()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Zwrot()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Naliczanie_kary()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Zagubienie_wypożyczonego_egzem()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Powiadomienie-przekroczenie_term_zwrotu()
	{
		throw new System.NotImplementedException();
	}

	public virtual void Prolongata()
	{
		throw new System.NotImplementedException();
	}

}

